### ISSUE TITLE
nerdtree-tabs panel shrinks horizontally

### ISSUE THREAD

**Issue by hiphamster** [jistr/vim-nerdtree-tabs#73]
When I start my Vim session, nerdtree-tabs panel looks right. I reveal and hide it frequently via NERDTreeTabsToggle. But after a while it starts to shrink horizontally, to the point where it becomes unusable. The only way to fix it is to restart vim, which obviously isn't desirable. I'm open to any suggestions on how to fix it, or how to debug it.

**Comment by tmsbrg** [comment]
Same problem. When opening new tabs, it shrinks very quickly. Whenever showing or hiding the panel the window shrinks more. It's really weird. This makes the plugin basically unusable for me right now, which sucks because I found it was just the thing for going through this huge codebase. It's weird because yesterday it seemed to work. I'm still figuring out why it's being like this.
